axelera-model-format: 1.0.0

name: mobilenetv2-imagenet-bowl

description: mobilenetv2 (ImageNet) from torchvision and bowl level dataset

pipeline:
  - mobilenetv2-imagenet-bowl:
      input:
        type: image
      preprocess:
        - resize:
            size: 256
        - centercrop:
            width: ${{input_width}}
            height: ${{input_height}}
        - torch-totensor:
        - normalize:
            mean: 0.485, 0.456, 0.406
            std: 0.229, 0.224, 0.225
      postprocess:
        - topk:
            k: 3

models:
  mobilenetv2-imagenet-bowl:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: mobilenetv2_bowl_level_classifier.onnx
    task_category: Classification
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 224, 224]
    input_color_format: RGB # RGB, BGR, Gray
    dataset: bowl-custom
    num_classes: 3
    # extra_kwargs:
    #   torchvision_args:
    #     torchvision_weights_args:
    #       object: MobileNet_V2_Weights
    #       name: IMAGENET1K_V1

datasets:
  bowl-custom:
    class: TorchvisionDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/torchvision.py
    data_dir_name: ImageNet
    labels_path: $AXELERA_FRAMEWORK/customers/datasets/labels/bowl.txt
    # Use COCO as representative images due to ImageNet's redistribution restrictions and large dataset size.
    # Suggest selecting 100-400 images from the ImageNet training dataset for representative images and
    # replacing the following representative_coco dataset with the selected images.
    repr_imgs_dir_path: $AXELERA_FRAMEWORK/customers/data/mobilenet_bowl/repr
    # repr_imgs_url: https://media.axelera.ai/artifacts/data/coco/coco2017_repr400.zip
    # repr_imgs_md5: b680128512392586e3c86b670886d9fa
    # cal_data: /path/to/the/cal/dir
    # val_data: /path/to/the/val/dir
