axelera-model-format: 1.0.0

name: yolo11m-v1-coco-custom

description: YOLO11M with custom objects (custom_bowl, custom_fountain)

pipeline:
  - detections:
      model_name: yolo11m-coco-onnx
      preprocess:
        - letterbox:
            width: 640
            height: 640
        - torch-totensor:
      postprocess:
        - decodeyolo:
            box_format: xywh
            normalized_coord: False
            # label_filter: ['cat', 'potted_plant', 'bowl']
            max_nms_boxes: 5000
            conf_threshold: 0.3
            nms_iou_threshold: 0.5
            nms_class_agnostic: False
            nms_top_k: 100
            use_multi_label: False

operators:
  decodeyolo:
    class: DecodeYolo
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yolo.py

models:
  yolo11m-coco-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: yolo11m_bowl_fountain_finetune.onnx
    # weight_url: https://media.axelera.ai/artifacts/model_cards/weights/yolo/object_detection/yolo11m.onnx
    # weight_md5: 8385c5e22f0d91eb20133afd021852c5
    task_category: ObjectDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    num_classes: 82
    dataset: CocoDataset-COCO2017
    extra_kwargs:
      aipu_cores: 1
      compilation_config:
        quantization_scheme: per_tensor_min_max
        ignore_weight_buffers: False


datasets: # Python dataloader
  CocoDataset-COCO2017:
    class: ObjDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    labels_path: $AXELERA_FRAMEWORK/customers/datasets/labels/yolo_custom.names
    label_type: COCO2017
    repr_imgs_dir_path: $AXELERA_FRAMEWORK/data/coco2017_400_b680128
    repr_imgs_url: https://media.axelera.ai/artifacts/data/coco/coco2017_repr400.zip
    repr_imgs_md5: b680128512392586e3c86b670886d9fa